package com.example.ordersentences.domain

enum class Tens {
    PAST_SIMPLE,
    PAST_CONTINUOUS,
    PAST_PERFECT,
    PAST_PERFECT_CONTINUOUS,

    PRESENT_SIMPLE,
    PRESENT_CONTINUOUS,
    PRESENT_PERFECT,
    PRESENT_PERFECT_CONTINUOUS,

    FUTURE_SIMPLE,
    FUTURE_CONTINUOUS,
    FUTURE_PERFECT,
    FUTURE_PERFECT_CONTINUOUS,
}